name: Builds

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build_cli:
    name: Build CLI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Update Go modules
        run: make dep

      - name: Build CLI
        run: make

      - name: Check version
        run: if [[ $(make version) == *"dirty"* ]]; then exit 1; fi
